services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspace
    volumes:
      - .:/workspace
      - frontend_node_modules:/workspace/frontend/node_modules
      - hardhat_node_modules:/workspace/hardhat-temp/node_modules
    ports:
      - "5173:5173" # Vite dev server
      - "8545:8545" # Hardhat local node
    stdin_open: true
    tty: true

volumes:
  frontend_node_modules:
  hardhat_node_modules:
